stages:
  load_data:
    cmd: python src/stage_01_load_save.py --config=config/config.yaml
    deps:
      - src/stage_01_load_save.py
      - src/util/all_utils.py
      - config/config.yaml
    outs:
      - artifacts/raw_local_dir/data.csv
